package nat20.kamppisserver.domain.enums

/**
 * TODO: Rename to Location
 * Finland's 50 largest cities sorted by number of citizens in descending order.
 */
enum class City {
    HELSINKI, ESPOO, TAMPERE, VANTAA, OULU, TURKU, JYVASKYLA, KUOPIO, LAHTI, PORI, KOUVOLA, JOENSUU, LAPPEENRANTA,
    HAMEENLINNA, VAASA, SEINAJOKA, ROVANIEMI, MIKKELI, SALO, KOTKA, PORVOO, KOKKOLA, HYVINKAA, LOHJA, JARVENPAA,
    NURMIJARVI, KIRKKONUMMI, TUUSULA, RAUMA, KERAVA, KAJAANI, KAARINA, NOKIA, YLOJARVI, KANGASALA, SAVONLINNA, VIHTI,
    RIIHIMAKI, RAASEPORI, IMATRA, RAISIO, RAAHE, LEMPAALA, SASTAMALA, HOLLOLA, SIPOO, TORNIO, SIILINJARVI, IISALMI,
    MANTSALA
}