version: "3.8"

services:
  spring-app:
    build: .
    container_name: kamppis-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/kamppisdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres-db:
    image: postgres:15
    container_name: kamppis-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kamppisdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
