### Get all users
GET http://localhost:8080/api/users/

### Get user with id = 1
GET http://localhost:8080/api/users/1

### Get all user profiles
GET http://localhost:8080/api/user-profiles

### Get all users who meet search criteria
// This requests initiates an SQL query from the database
// The request gets the user's id as a path variable
// The server looks up this user's search criteria (by user's id)
// And returns all profiles that meet the user's search criteria
GET http://localhost:8080/api/user-profiles/2/query

### Get authentication token for alice smith (save it in auth_token for the following request)
POST http://localhost:8080/api/login?
    email=alice.smith@example.com

> {%
    client.global.set("auth_token", response.body.token);
%}

### Use the above token to access a protected endpoint
GET http://localhost:8080/api/login/protected
Authorization: Bearer {{auth_token}}

### Example using expired token
GET http://localhost:8080/api/login/protected
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsImlhdCI6MTc0MjA3MDA1MCwiZXhwIjoxNzQyMDczNjUwfQ.hRqdcGM3hDrXdbRZShNzhmWcqiTHmOIbKYXRdZnY6V_XPortA-LaZAFvn-ru4t8WTMsGYsv8BtEqzhbCUImfnw

### Get all room profiles
GET http://localhost:8080/api/room-profiles

### Get room profile by id
GET http://localhost:8080/api/room-profiles/1

