### Get all users
GET http://localhost:8080/api/users

### Get user with id = 1
GET http://localhost:8080/api/users/1
Authorization: Bearer {{auth_token}}

### Get all user profiles
GET http://localhost:8080/api/user-profiles
Authorization: Bearer {{auth_token}}

### Get user profile with id = 1
GET http://localhost:8080/api/user-profiles/1
Authorization: Bearer {{auth_token}}

### Get profile with id = 1
GET http://localhost:8080/api/profiles/1
Authorization: Bearer {{auth_token}}

### Get profile with id = 79
GET http://localhost:8080/api/profiles/79
Authorization: Bearer {{auth_token}}


### Get all users who meet search criteria
// This requests initiates an SQL query from the database
// The request gets the user's id as a path variable
// The server looks up this user's search criteria (by user's id)
// And returns all profiles that meet the user's search criteria
GET http://localhost:8080/api/user-profiles/1/query?size=2
Authorization: Bearer {{auth_token}}

### Get all rooms that meet search criteria
// This requests initiates an SQL query from the database
// The request gets the user's id as a path variable
// The server looks up this user's search criteria (by user's id)
// And returns all rooms that meet the user's search criteria
GET http://localhost:8080/api/room-profiles/27/query?size=2
Authorization: Bearer {{auth_token}}

### Get authentication token for alice smith (save it in auth_token for the following request)
POST http://localhost:8080/api/login/mock?
    email=alice.smith@example.com

> {%
    client.global.set("auth_token", response.body.token);
%}

### Use the above token to access a protected endpoint
GET http://localhost:8080/api/login/protected
Authorization: Bearer {{auth_token}}

### Example using expired token
GET http://localhost:8080/api/login/protected
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsImlhdCI6MTc0MjA3MDA1MCwiZXhwIjoxNzQyMDczNjUwfQ.hRqdcGM3hDrXdbRZShNzhmWcqiTHmOIbKYXRdZnY6V_XPortA-LaZAFvn-ru4t8WTMsGYsv8BtEqzhbCUImfnw

### Get all room profiles
GET http://localhost:8080/api/room-profiles
Authorization: Bearer {{auth_token}}

### Get room profile by id
GET http://localhost:8080/api/room-profiles/96
Authorization: Bearer {{auth_token}}

### Post a new room profile
POST http://localhost:8080/api/room-profiles
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userIds": [5,6],
  "flatId": 2,
  "rent": 750,
  "isPrivateRoom": true,
  "furnished": true,
  "furnishedInfo": "Heinäpaalisänky",
  "bio": "Kiva lato. Heinäpaalit kullekin."
}

### Update a room profile
PUT http://localhost:8080/api/room-profiles/97
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userIds": [5,6,7],
  "flatId": 2,
  "rent": 150,
  "isPrivateRoom": true,
  "furnished":  false,
  "bio": "Lato paloi. Samoin heinäpaalit. Kiva tuhkakasa missä lämmin yöpyä."
}

### Get all flats
GET http://localhost:8080/api/flats
Authorization: Bearer {{auth_token}}

### Get flat by id
GET http://localhost:8080/api/flats/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Post a new flat
POST http://localhost:8080/api/flats
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "McMansion",
  "description": "Seinät muovia, aidat muovia, puut muovia.",
  "location": "ESPOO",
  "totalRoommates": 13,
  "flatUtilities": [
    "WIFI",
    "BALCONY"
  ]
}

### Update flat
PUT http://localhost:8080/api/flats/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "McMansion2",
  "description": "Seinät muovia, aidat muovia, puut muovia. Muooooovia.",
  "location": "HELSINKI",
  "totalRoommates": 15,
  "flatUtilities": [
    "WIFI",
    "BALCONY",
    "DISHWASHER"
  ],
  "roomProfileIds": [90]
}

### UserProfile swipes RoomProfile
POST http://localhost:8080/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 1,
  "swipedProfileId": 71,
  "isRightSwipe": true
}

### RoomProfile swipes UserProfile
POST http://localhost:8080/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 4,
  "swipedProfileId": 5,
  "isRightSwipe": true
}

### UserProfile swipes RoomProfile
POST http://localhost:8080/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 12,
  "swipedProfileId": 81,
  "isRightSwipe": true
}

### RoomProfile swipes UserProfile
POST http://localhost:8080/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 1,
  "swipedProfileId": 27,
  "isRightSwipe": true
}

### UserProfile swipes RoomProfile
POST https://kamppis.hellmanstudios.fi/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 27,
  "swipedProfileId": 81,
  "isRightSwipe": true
}

### RoomProfile swipes UserProfile
POST https://kamppis.hellmanstudios.fi/api/swipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "swipingProfileId": 81,
  "swipedProfileId": 27,
  "isRightSwipe": true
}


### Get authentication token for alice smith (save it in auth_token for the following request)
POST https://kamppis.hellmanstudios.fi/api/login/mock?
    email=alice.smith@example.com

> {%
    client.global.set("auth_token", response.body.token);
%}

### Use the above token to access a protected endpoint
GET https://kamppis.hellmanstudios.fi/api/login/protected
Authorization: Bearer {{auth_token}}

### Example using expired token
GET https://kamppis.hellmanstudios.fi/api/login/protected
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsImlhdCI6MTc0MjA3MDA1MCwiZXhwIjoxNzQyMDczNjUwfQ.hRqdcGM3hDrXdbRZShNzhmWcqiTHmOIbKYXRdZnY6V_XPortA-LaZAFvn-ru4t8WTMsGYsv8BtEqzhbCUImfnw

### Get server health
GET https://kamppis.hellmanstudios.fi/api/health

### Get db health
GET https://kamppis.hellmanstudios.fi/api/db-health

###
GET https://kamppis.hellmanstudios.fi/api/user-profiles/2/query?size=2
Authorization: Bearer {{auth_token}}


